In [1]:
class MaxCounter:
    def __init__(self):
        self.cur_max = -10**10
    
    def add(self, num):
        if num > self.cur_max:
            self.cur_max = num
    
    def print_max(self):
        print("Текущий максимум:", self.cur_max)

In [6]:
max_counter = MaxCounter()
max_counter.add(30)
max_counter.add(20)
max_counter.add(1)
max_counter.add(100)

In [7]:
max_counter.print_max()

Текущий максимум: 100


In [8]:
max_counter.add(1000)
max_counter.add(-1)
max_counter.print_max()

Текущий максимум: 1000


In [10]:
max_counter.cur_max

1000

In [11]:
max_counter2 = MaxCounter()
max_counter2.add(0.4)
max_counter2.add(1.1)
max_counter2.print_max()

Текущий максимум: 1.1


In [12]:
max_counter2.cur_max

1.1

In [4]:
def add(num, cur_max):
    if num > cur_max:
        return num
    else:
        return cur_max


cur_max = -10**10
cur_max = add(30, cur_max)
cur_max = add(20, cur_max)

In [5]:
cur_max

30

In [33]:
from collections import Counter

In [29]:
count = Counter()
count.update(["my", "cat", "sleeps"])
count.update(["my", "cat", "plays"])
count.update(["my", "dog", "runs"])

In [30]:
count.most_common(n=2)

[('my', 3), ('cat', 2)]

In [39]:
class MyCounter:
    def __init__(self):
        self.dct = {}

    def update(self, elems):
        for elem in elems:
            if not elem in self.dct:
                self.dct[elem] = 0
            self.dct[elem] += 1
    
    def most_common(self, n=None):
        # print(self.dct.items())
        sorted_items = sorted(self.dct.items(), key=lambda x:x[1], \
                              reverse=True)
        
        print(sorted_items[:n])

In [40]:
count = MyCounter()
count.update(["my", "cat", "sleeps"])
count.update(["my", "cat", "plays"])
count.update(["my", "dog", "runs"])
count.most_common(n=2)
count.most_common()

[('my', 3), ('cat', 2)]
[('my', 3), ('cat', 2), ('sleeps', 1), ('plays', 1), ('dog', 1), ('runs', 1)]


In [49]:
count = MyCounter()
count.update([1, 10, 5])
count.update([7, 1, 10])
count.most_common(n=2)
count.most_common()

[(1, 2), (10, 2)]
[(1, 2), (10, 2), (5, 1), (7, 1)]


In [37]:
count.dct

{'cat': 2, 'dog': 1, 'my': 3, 'plays': 1, 'runs': 1, 'sleeps': 1}

In [38]:
count.dct.items()

dict_items([('my', 3), ('cat', 2), ('sleeps', 1), ('plays', 1), ('dog', 1), ('runs', 1)])

In [ ]:
class MyCounter:
    def __init__(self):
        self.dct = {}
    def update(self, elems):
        
    
    def most_common(self, n=None):
        print(self.dct.items())

In [45]:
class MinMaxCounter:
    def __init__(self, search_max=True):
        self.cur_opt = -10**10 if search_max else 10**10
        self.search_max = search_max
    
    def add(self, num):
        if self.search_max:
            if num > self.cur_opt:
                self.cur_opt = num
        else:
            if num < self.cur_opt:
                self.cur_opt = num
    
    def print_opt(self):
        print("Текущий оптимум:", self.cur_opt)

In [47]:
max_counter = MinMaxCounter()
max_counter.add(30)
max_counter.add(20)
max_counter.add(1)
max_counter.add(100)
max_counter.print_opt()

Текущий оптимум: 100


In [48]:
max_counter = MinMaxCounter(search_max=False)
max_counter.add(30)
max_counter.add(20)
max_counter.add(1)
max_counter.add(100)
max_counter.print_opt()

Текущий оптимум: 1


In [53]:
from sklearn.datasets import load_boston
data = load_boston()
X = data["data"]
y = data["target"]
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y) 

In [55]:
data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [56]:
data["feature_names"]

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [54]:
X_tr.shape, X_te.shape, y.shape

((379, 13), (127, 13), (506,))

In [58]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_tr, y_tr)
preds_te = model.predict(X_te)


In [60]:
model.coef_

array([-1.39340723e-01,  4.91416361e-02, -6.65362893e-03,  3.59911050e+00,
       -1.65476526e+01,  3.83934523e+00, -1.33996547e-02, -1.74809237e+00,
        2.78164112e-01, -1.03685497e-02, -8.14807284e-01,  1.02274725e-02,
       -5.13222267e-01])

In [59]:
preds_te

array([13.81526622, 14.06478307, 17.83736509, 21.1521442 , 21.06155915,
       22.00452397, 19.76569846, 34.6880118 , 31.72041119, 14.33632523,
       19.73957403, 28.09517119, 20.09406153, 21.76978836, 22.59128985,
       17.59273705, 20.37204308, 25.48790125, 21.64412136, 19.94532444,
       21.49406636, 19.08881453, 35.84498856, 26.18175325, 14.04866427,
       14.57198282, 20.51710997, 24.0773428 , 32.61265297, 19.25501467,
       12.75499502, 24.3850759 ,  4.06289696, 28.59818188, 16.9647455 ,
       23.13580146, 38.99356623, 22.52856409, 23.65940526, 12.83626879,
       15.58242379, 38.01003925, 42.95075284, 18.0700071 , 17.1875888 ,
       18.27831072, 19.64222829, 15.82170733, 27.07291946, 26.65400987,
       33.67871497, 22.95679406, 34.76320071, 20.99257119, 32.45990363,
       22.52572635, 19.37315734, 19.38959131, 31.00203925, 23.86621168,
       24.05351074, 15.99703199, 25.26776725, 22.91575461, 32.74215884,
       33.89303849, 18.81399291, 18.35058438, 14.47567524,  6.77

In [80]:
import numpy as np
class DummyRegressor:
    def __init__(self, use_median=False):
        self.use_median = use_median
    
    def fit(self, X, y):
        if self.use_median:
            self.constant = np.median(y)
        else:
            self.constant = np.mean(y)
        
    def predict(self, X):
        preds = np.ones(X.shape[0]) * self.constant
        return preds

In [81]:
dummy = DummyRegressor(use_median=True)
dummy.fit(X_tr, y_tr)
dummy.predict(X_te)

array([21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4, 21.4,
       21.4, 21.4, 21.4, 21.4, 21.4, 21.4])

In [82]:
dummy.constant

21.4

In [ ]:
class LinearRegressor:
    def fit(self, X, y):
        
    def predict(self, X):
        

In [ ]:
np.mean
np.median

In [68]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_tr)
X_tr_sc = scaler.transform(X_tr)
X_te_sc = scaler.transform(X_te)

In [69]:
X_tr[0]

array([1.3110e-02, 9.0000e+01, 1.2200e+00, 0.0000e+00, 4.0300e-01,
       7.2490e+00, 2.1900e+01, 8.6966e+00, 5.0000e+00, 2.2600e+02,
       1.7900e+01, 3.9593e+02, 4.8100e+00])

In [70]:
X_tr_sc[0]

array([7.63179629e-05, 9.00000000e-01, 2.78592375e-02, 0.00000000e+00,
       3.70370370e-02, 7.14175058e-01, 1.95674562e-01, 7.89817028e-01,
       1.73913043e-01, 7.26577438e-02, 5.63829787e-01, 9.97554087e-01,
       8.49889625e-02])