In [1]:
from sklearn.datasets import load_boston
data = load_boston()
X = data["data"]
y = data["target"]
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y) 

In [55]:
data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [56]:
data["feature_names"]

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [54]:
X_tr.shape, X_te.shape, y.shape

((379, 13), (127, 13), (506,))

In [2]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_tr, y_tr)
preds_te = model.predict(X_te)


In [3]:
model.coef_

array([-9.56823701e-02,  4.96612667e-02, -4.37427298e-03,  3.11116892e+00,
       -1.71648997e+01,  3.48569068e+00,  1.49845255e-02, -1.41946809e+00,
        2.84472746e-01, -1.16643550e-02, -9.61845027e-01,  5.40806857e-03,
       -5.87318397e-01])

In [59]:
preds_te

array([13.81526622, 14.06478307, 17.83736509, 21.1521442 , 21.06155915,
       22.00452397, 19.76569846, 34.6880118 , 31.72041119, 14.33632523,
       19.73957403, 28.09517119, 20.09406153, 21.76978836, 22.59128985,
       17.59273705, 20.37204308, 25.48790125, 21.64412136, 19.94532444,
       21.49406636, 19.08881453, 35.84498856, 26.18175325, 14.04866427,
       14.57198282, 20.51710997, 24.0773428 , 32.61265297, 19.25501467,
       12.75499502, 24.3850759 ,  4.06289696, 28.59818188, 16.9647455 ,
       23.13580146, 38.99356623, 22.52856409, 23.65940526, 12.83626879,
       15.58242379, 38.01003925, 42.95075284, 18.0700071 , 17.1875888 ,
       18.27831072, 19.64222829, 15.82170733, 27.07291946, 26.65400987,
       33.67871497, 22.95679406, 34.76320071, 20.99257119, 32.45990363,
       22.52572635, 19.37315734, 19.38959131, 31.00203925, 23.86621168,
       24.05351074, 15.99703199, 25.26776725, 22.91575461, 32.74215884,
       33.89303849, 18.81399291, 18.35058438, 14.47567524,  6.77

### Linear regression

In [8]:
import numpy as np
class MyLinearRegression:
    def fit(self, X, y):
        ### find weights and save in self.
        XTX = np.dot(X.T, X)
        XTX_inv = np.linalg.inv(XTX)
        XTY = np.dot(X.T, y)
        w = np.dot(XTX_inv, XTY)
        self.weights = w
        
    def predict(self, X):
        preds = np.dot(X, self.weights)
        return preds

In [13]:
model = MyLinearRegression()
model.fit(X_tr, y_tr)
preds1 = model.predict(X_te)
preds[:10]

array([21.32593648, 20.89158022, 17.92066068, 22.15638276, 18.91709258,
       31.20848543,  5.509698  ,  7.85928213, 37.00431803, 21.37957418])

In [14]:
model = LinearRegression(fit_intercept=False)
model.fit(X_tr, y_tr)
preds2 = model.predict(X_te)
preds[:10]

array([21.32593648, 20.89158022, 17.92066068, 22.15638276, 18.91709258,
       31.20848543,  5.509698  ,  7.85928213, 37.00431803, 21.37957418])

In [19]:
(preds1==preds2).all()

False

In [18]:
(np.abs(preds1-preds2) < 1e-10).all()

True